# Lab4 (PART 1)
Name: Birva Babaria || Rollno: CE010 || ID: 19CEUON064

### ***Linear regression model from scratch*** 

In [1]:
import numpy as np
import torch

In [2]:
inputs = np.array([[73, 67, 43],
[91, 88, 64],
[87, 134, 58],
[102, 43, 37],
[69, 96, 70]], dtype='float32')

In [3]:
targets = np.array([[56],
[81],
[119],
[22],
[103]], dtype='float32')

In [4]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)

In [5]:
weight = torch.randn(2, 3, requires_grad=True)
bias = torch.randn(2, requires_grad=True)

In [9]:
inputs @ weight.t() + bias

tensor([[208.2393, -36.5961],
        [270.7560, -45.8415],
        [372.1846, -46.3467],
        [174.1618, -49.4186],
        [273.4664, -35.5742]], grad_fn=<AddBackward0>)

In [10]:
def model(inputs):
    return inputs @ weight.t() + bias

In [11]:
prediction = model(inputs)
print(prediction)

tensor([[208.2393, -36.5961],
        [270.7560, -45.8415],
        [372.1846, -46.3467],
        [174.1618, -49.4186],
        [273.4664, -35.5742]], grad_fn=<AddBackward0>)


### ***Loss function*** 

In [12]:
diff0 = prediction - targets
torch.sum(diff0 * diff0) / diff0.numel()

tensor(25180.4414, grad_fn=<DivBackward0>)

In [13]:
def mse(t1, t2):
    diff = t1 - t2
    return torch.sum(diff * diff) / diff.numel()

In [14]:
loss = mse(prediction, targets)
print(loss)

tensor(25180.4414, grad_fn=<DivBackward0>)


### ***Compute gradients*** 

In [15]:
loss.backward()
print(weight.grad)
print(bias.grad)

tensor([[ 15538.2031,  16746.6074,  10187.6045],
        [ -9906.7148, -11179.3145,  -6806.4561]])
tensor([ 183.5616, -118.9554])


### ***Train the model using gradient descent*** 

In [16]:
with torch.no_grad():
    weight -= weight.grad * 1e-5
    bias -= bias.grad * 1e-5
    weight.grad.zero_()
    bias.grad.zero_()

In [17]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(17030.2305, grad_fn=<DivBackward0>)


In [18]:
for i in range(100):
    prediction = model(inputs)
    loss = mse(prediction, targets)
    loss.backward()
    with torch.no_grad():
        weight -= weight.grad * 1e-5
        bias -= bias.grad * 1e-5
        weight.grad.zero_()
        bias.grad.zero_()

In [19]:
prediction = model(inputs)
loss = mse(prediction, targets)
print(loss)

tensor(100.4828, grad_fn=<DivBackward0>)


In [20]:
prediction

tensor([[ 57.8426,  59.9229],
        [ 73.9780,  82.3514],
        [136.3170, 113.9337],
        [ 24.8217,  36.0992],
        [ 85.2846,  93.5779]], grad_fn=<AddBackward0>)

In [22]:
targets

tensor([[ 56.],
        [ 81.],
        [119.],
        [ 22.],
        [103.]])